export const VIDEO_FETCH_ALL_VIDEO = 'VIDEO_FETCH_ALL_VIDEO';
export const VIDEO_FETCH_VIDEOS_BEGIN = 'VIDEO_FETCH_VIDEOS_BEGIN';
export const VIDEO_FETCH_VIDEOS_SUCCESS = 'VIDEO_FETCH_VIDEOS_SUCCESS';
export const VIDEO_FETCH_VIDEOS_FAILURE = 'VIDEO_FETCH_VIDEOS_FAILURE';
export const VIDEO_FETCH_VIDEOS_DISMISS_ERROR = 'VIDEO_FETCH_VIDEOS_DISMISS_ERROR';
export const VIDEO_HANDLE_PAGES = 'VIDEO_HANDLE_PAGES';
